CLIENT_NAME:=meineBox
SERVER_NAME:=meineBox_server

SRC_FOLDER_PATH:=src
BIN_FOLDER_PATH:=bin
OBJ_FOLDER_PATH:=obj

CLIENT_SRC:=$(SRC_FOLDER_PATH)/$(CLIENT_NAME).cpp
CLIENT_BIN:=$(BIN_FOLDER_PATH)/$(CLIENT_NAME)
CLIENT_OBJ:=$(OBJ_FOLDER_PATH)/$(CLIENT_NAME).o
SERVER_SRC:=$(SRC_FOLDER_PATH)/$(SERVER_NAME).cpp
SERVER_BIN:=$(BIN_FOLDER_PATH)/$(SERVER_NAME)
SERVER_OBJ:=$(OBJ_FOLDER_PATH)/$(SERVER_NAME).o

CC:=g++

.PHONY: all clean distclean

all: $(CLIENT_BIN) $(SERVER_BIN)

$(CLIENT_BIN): $(CLIENT_OBJ)
	$(CC) -o $(CLIENT_BIN) $(CLIENT_OBJ)

$(CLIENT_OBJ): $(CLIENT_SRC)
	$(CC) -c $(CLIENT_SRC)
	mv ./$(CLIENT_NAME).o $(CLIENT_OBJ)

$(SERVER_BIN): $(SERVER_OBJ)
	$(CC) -o $(SERVER_BIN) $(SERVER_OBJ)

$(SERVER_OBJ): $(SERVER_SRC)
	$(CC) -c $(SERVER_SRC)
	mv ./$(SERVER_NAME).o $(SERVER_OBJ)

clean:
	rm -f $(OBJ_FOLDER_PATH)/*.o 
distclean: clean
	rm -f $(CLIENT_BIN) $(SERVER_BIN)
