#ifndef __GLOBAL_DEFINITIONS_HPP
#define __GLOBAL_DEFINITIONS_HPP

// MeineBox
#define MEINEBOX_VERSION 0.1

// OS ENVIROMENT 
#define SYNCRONIZE_FOLDER "~/sync_dir" 

// SOCKETS
#define SENTINEL_SOCKET_PORT 7779
#define SENTINEL_SOCKET_QUEUE_CAPACITY 10
#define DATA_COMMUNICATION_BUFFER_CAPACITY 1024

// DATAGRAM COMMUNICATION
#define USER_DATAGRAM_LOGIN_REQUEST         0x0000
#define USER_DATAGRAM_REGISTER_REQUEST      0x0001
#define USER_DATAGRAM_START_REQUEST         0x0002
#define USER_DATAGRAM_STATUS_REQUEST        0x0003
#define USER_DATAGRAM_STOP_REQUEST          0x0004
#define USER_DATAGRAM_SYNCRONIZE_REQUEST    0x0005
#define USER_DATAGRAM_SENDING_DATA          0x0006

#define SERVER_DATAGRAM_SYNCRONIZE_ORDER    0x0007
#define SERVER_DATAGRAM_SENDING_DATA        0x0008

#endif