#ifndef __GLOBAL_DEFINITIONS_HPP
#define __GLOBAL_DEFINITIONS_HPP

// MeineBox
#define MEINEBOX_VERSION 0.1

// OS ENVIROMENT 
#define SYNCRONIZE_FOLDER "~/sync_dir" 

// SOCKETS
#define SENTINEL_SOCKET_PORT 7779
#define SENTINEL_SOCKET_QUEUE_CAPACITY 10
#define DATA_COMMUNICATION_BUFFER_CAPACITY 1024


#endif